### ISSUE TITLE
Add functionality for plotting results of selection rule regrets

### ISSUE THREAD

**Issue by thcrock** [dssg/audition#11]
@shaycrk we had talked about this a while ago. I think you said the functionality we want here would be a plot similar to the best-distance plot, but the distance being measured is the regret, and the lines would be selection rules instead of model groups. Is this accurate?

**Comment by thcrock** [comment]
Talked to Kit, this is accurate. We also want to plot regret over time at this same phase, similar to the metrics over time graph.

**Comment by thcrock** [comment]
We want to interface with this via a compact configuration. Example:

```
rule_groups:
    -
        shared_parameters:
            -
                metric: precision
                parameter: 100_abs
            -
                metric: recall
                parameter: 100_abs
        selection_rules: 
            -
                name: most_frequent_best_dist
                best_dist: [0.1, 0.2, 0.3]
            -
                name: best_average_two_metrics
                metric1: precision
                parameter1: 100_abs
```
